### PR TITLE
Update to March 2015 versions of tools and libs

### PR DESCRIPTION
**Pull request by mirogta**
Updated solution to VS2013
Updated Castle.Windsor and Castle.Core to 3.3,0
Targeting .NET framework 4.5.2
Updated version to 0.4.0

### CODE REVIEW

**Comment by jhuntoo** [comment]
Any plans to get this merged and released? This would be really helpful as I'm on  3.3.0

**Comment by mirogta** [comment]
@jhuntoo Not sure if you know, but you can build it from the source in my fork https://github.com/mirogta/Castle.Windsor.Lifestyles while waiting for the pull request to be accepted. Hope this helps.

**Comment by jhuntoo** [comment]
Hi, @mirogta yes that's an option. However the reason I need this in the first place is to purge all non-Nuget  dependencies from my company's solution, they are a maintenance overhead compared to using Nuget. 

To complicate matters, Windsor Castle doesn't honour binding redirects when using    container.Install(FromAssembly.InDirectory(....)).

So I've written some slighly hacky code which listens for the assembly load failed event. If this PR were released I could remove it entirely. It's a legacy codebase so changing the Windsor assembling loading code isn't really an option.

```csharp
RedirectAssembly("Castle.Windsor", new Version(3, 3, 0, 0), "407dd0808d44fbdc");

public static void RedirectAssembly(string shortName, Version targetVersion, string publicKeyToken)
        {
            ResolveEventHandler handler = null;
            handler = (sender, args) =>
            {
                var requestedAssembly = new AssemblyName(args.Name);
                if (requestedAssembly.Name != shortName)
                    return null;
                requestedAssembly.Version = targetVersion;
                requestedAssembly.SetPublicKeyToken(new AssemblyName("x, PublicKeyToken=" + publicKeyToken).GetPublicKeyToken());
                requestedAssembly.CultureInfo = CultureInfo.InvariantCulture;
                AppDomain.CurrentDomain.AssemblyResolve -= handler;
                return Assembly.Load(requestedAssembly);
            };
            AppDomain.CurrentDomain.AssemblyResolve += handler;
        }
```

**Comment by mausch** [comment]
It's late here now, but I'll merge it soon, probably tomorrow.

**Comment by mausch** [comment]
Merged, thanks!

**Comment by mausch** [comment]
And released: https://www.nuget.org/packages/Castle.Windsor.Lifestyles/0.4.0

**Comment by mirogta** [comment]
Thanks :)

**Pull request merged**
